### ISSUE TITLE
Error when adding WMTS layer

### ISSUE THREAD

**Issue by hblitza** [terrestris/shogun-core#398]
Error occurs when adding a WMTS thorugh shogun2-webapp panel. GetCapabilities is successfull, the layer list is shown and a layer can be selected+added to the application. On layer preview/load in application this error occurs:

`shogun-webapp_1         | 14:11:14.322 ERROR de.terrestris.shoguncore.service.GeoServerInterceptorService.getMostSpecificRule() @657 - Got no interceptor rules for this request/response. Usually this should not happen as one has to define at least the basic sets of rules (e.g. ALLOW all WMS requests) when using the interceptor.`

Current master branch shogun2-webapp

**Comment by weskamm** [comment]
Well, i think this is an issue of the the getMostSpecificRule Method.
It may be the case that your newly created layer does not have any rules set. But in my opinion these rules do not need to exist explicitly, as the layer itself is secured through the service methods and permission evaluators anyway.

I think fixing the line
https://github.com/terrestris/shogun-core/blob/61176ac096023ab00abe1bcf8f25b50dd04be4ac/src/shogun-core-main/src/main/java/de/terrestris/shoguncore/service/GeoServerInterceptorService.java#L661
to return null instead of an exception could fix the issue

**Comment by weskamm** [comment]
fixed by adding missing rules in shogun webapp
